# Generated by Django 3.0.6 on 2020-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttype', models.IntegerField()),
                ('mail', models.TextField()),
                ('converted_text', models.BinaryField()),
            ],
        ),
    ]
