# Generated by Django 3.0.6 on 2020-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='file_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
